name: flowcase
description: A Flutter Showcase project, showing small features at a time.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_settings_screens: ^0.3.3-null-safety+2
  google_fonts: ^4.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.11.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/
    - lib/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.png"

